packages:
  - 'packages/*'
  - 'apps/*'
overrides:
  yauzl: ^3.3.1
allowBuilds:
  '@esbuild/win32-x64': true
  '@eslint-community/eslint-utils': true
  '@eslint-community/regexpp': true
  '@eslint/config-array': true
  '@eslint/config-helpers': true
  '@eslint/core': true
  '@eslint/eslintrc': true
  '@eslint/js': true
  '@eslint/object-schema': true
  '@eslint/plugin-kit': true
  '@humanfs/core': true
  '@humanfs/node': true
  '@humanfs/types': true
  '@humanwhocodes/module-importer': true
  '@humanwhocodes/retry': true
  '@jest/schemas': true
  '@jridgewell/sourcemap-codec': true
  '@nodelib/fs.scandir': true
  '@nodelib/fs.stat': true
  '@nodelib/fs.walk': true
  '@rollup/rollup-win32-x64-gnu': true
  '@rollup/rollup-win32-x64-msvc': true
  '@sinclair/typebox': true
  '@types/estree': true
  '@types/json-schema': true
  '@types/node': true
  '@typescript-eslint/eslint-plugin': true
  '@typescript-eslint/parser': true
  '@typescript-eslint/scope-manager': true
  '@typescript-eslint/type-utils': true
  '@typescript-eslint/types': true
  '@typescript-eslint/typescript-estree': true
  '@typescript-eslint/utils': true
  '@typescript-eslint/visitor-keys': true
  '@vitest/expect': true
  '@vitest/runner': true
  '@vitest/snapshot': true
  '@vitest/spy': true
  '@vitest/utils': true
  acorn: true
  acorn-jsx: true
  acorn-walk: true
  ajv: true
  ansi-styles: true
  argparse: true
  array-union: true
  assertion-error: true
  balanced-match: true
  brace-expansion: true
  braces: true
  cac: true
  callsites: true
  chai: true
  chalk: true
  check-error: true
  color-convert: true
  color-name: true
  concat-map: true
  confbox: true
  cross-spawn: true
  debug: true
  deep-eql: true
  deep-is: true
  diff-sequences: true
  dir-glob: true
  electron: true
  esbuild: true
  escape-string-regexp: true
  eslint: true
  eslint-config-prettier: true
  eslint-scope: true
  eslint-visitor-keys: true
  espree: true
  esquery: true
  esrecurse: true
  estraverse: true
  estree-walker: true
  esutils: true
  execa: true
  fast-deep-equal: true
  fast-glob: true
  fast-json-stable-stringify: true
  fast-levenshtein: true
  fastq: true
  file-entry-cache: true
  fill-range: true
  find-up: true
  flat-cache: true
  flatted: true
  get-func-name: true
  get-stream: true
  glob-parent: true
  globals: true
  globby: true
  graphemer: true
  has-flag: true
  human-signals: true
  ignore: true
  import-fresh: true
  imurmurhash: true
  is-extglob: true
  is-glob: true
  is-number: true
  is-stream: true
  isexe: true
  js-tokens: true
  js-yaml: true
  json-buffer: true
  json-schema-traverse: true
  json-stable-stringify-without-jsonify: true
  keyv: true
  levn: true
  local-pkg: true
  locate-path: true
  lodash.merge: true
  loupe: true
  magic-string: true
  merge-stream: true
  merge2: true
  micromatch: true
  mimic-fn: true
  minimatch: true
  mlly: true
  ms: true
  nanoid: true
  natural-compare: true
  npm-run-path: true
  onetime: true
  optionator: true
  p-limit: true
  p-locate: true
  parent-module: true
  path-exists: true
  path-key: true
  path-type: true
  pathe: true
  pathval: true
  picocolors: true
  picomatch: true
  pkg-types: true
  playwright: true
  postcss: true
  prelude-ls: true
  prettier: true
  pretty-format: true
  punycode: true
  queue-microtask: true
  react-is: true
  resolve-from: true
  reusify: true
  rollup: true
  run-parallel: true
  semver: true
  shebang-command: true
  shebang-regex: true
  siginfo: true
  signal-exit: true
  slash: true
  source-map-js: true
  stackback: true
  std-env: true
  strip-final-newline: true
  strip-json-comments: true
  strip-literal: true
  supports-color: true
  tinybench: true
  tinypool: true
  tinyspy: true
  to-regex-range: true
  ts-api-utils: true
  tsx: true
  type-check: true
  type-detect: true
  typescript: true
  typescript-eslint: true
  ufo: true
  undici-types: true
  uri-js: true
  vite: true
  vite-node: true
  vitest: true
  which: true
  why-is-node-running: true
  word-wrap: true
  yocto-queue: true
